spring:
  application:
    name: bff-agendador-tarefas

usuario:
  url: http://localhost:8080/usuario

agendador:
  url: http://localhost:8081/tarefas

notificacao:
  url: http://localhost:8082/email

server:
  port: 8083
